-- Criacao de tabelas

CREATE TABLE Produto(
	Codigo_Barras INT PRIMARY KEY,
	Nome VARCHAR (60) NOT NULL,
	Marca VARCHAR (40),
	Tipo VARCHAR (40) NOT NULL,
	Unidade_Volume VARCHAR (20) NOT NULL
);

CREATE TABLE Campanha(
	Nome VARCHAR (70) PRIMARY KEY,
	Estado BOOLEAN DEFAULT TRUE NOT NULL,
	D_ini TIMESTAMP NOT NULL,
	D_fim TIMESTAMP

	CONSTRAINT CK_DATA
		CHECK (D_ini <= D_fim)
);

CREATE TABLE Doacao(
	Quantidade INT NOT NULL,
	Campanha VARCHAR (70) NOT NULL,
	Codigo_Barras INT NOT NULL,

 	CONSTRAINT FK_PRODUTO
		FOREIGN KEY (Codigo_Barras) REFERENCES Produto (Codigo_Barras)
		ON DELETE CASCADE,

	CONSTRAINT FK_CAMPANHA
		FOREIGN KEY (Campanha) REFERENCES Campanha (Nome)
		ON DELETE CASCADE,

	CONSTRAINT PK_DOACAO
		PRIMARY KEY (Campanha, Codigo_Barras)

);